<?xml version="1.0"?>
<robot name="linorobot2_2wd" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find linorobot2_description)/urdf/mecanum_properties.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/base.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/mecanum_wheel.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/mecanum_wheel2.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/imu.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/generic_laser.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/depth_sensor.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/controllers/omni_drive.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/robots/suspention.urdf.xacro" />

 <xacro:property name="teker" value="-0.4" />

  <xacro:base 
    length="${base_length}" 
    width="${base_width}" 
    height="${base_height}" 
    mass="${base_mass}"
    wheel_radius="${wheel_radius}"
    wheel_pos_z="${wheel_pos_z}"
/>

  <xacro:mecanum_wheel2 
    side="front_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x-0.02}" 
    pos_y="0.1" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
    yon="-1.57"
  />

  <xacro:mecanum_wheel 
    side="front_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x-0.02}" 
    pos_y="${teker}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
    yon="1.57"
    
  />
  <xacro:mecanum_wheel 
    side="rear_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x+0.075}" 
    pos_y="0.202" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
    yon="-1.57"

  />

  <xacro:mecanum_wheel2 
    side="rear_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x+0.075}" 
    pos_y="${teker-0.105}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
    yon="1.57"

  />
  
  <xacro:suspention 
    side="front_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="0.31" 
    pos_y="0.23" 
    pos_z="0.235" 
    mass="0"
    yon="0"
    yonp="-0.8"

  />
   <xacro:suspention 
    side="front_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="0.31" 
    pos_y="-0.23" 
    pos_z="0.235" 
    mass="0"
    yon="0"
    yonp="-0.8"
  />
   <xacro:suspention 
    side="rear_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="-0.255" 
    pos_y="-0.225" 
    pos_z="0.235" 
    mass="0"
    yon="0"
    yonp="0.8"

  />
   <xacro:suspention 
    side="rear_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="-0.255" 
    pos_y="0.225" 
    pos_z="0.235" 
    mass="0"
    yon="0"
    yonp="0.8"


  />

  
  <xacro:imu/>
  
  <xacro:generic_laser>
    <xacro:insert_block name="laser_pose" />
  </xacro:generic_laser>
  
  <xacro:depth_sensor>
    <xacro:insert_block name="depth_sensor_pose" />
  </xacro:depth_sensor>

  <xacro:omni_drive_controller/>
</robot>